Repository Kernel-GL-HRK/gl-kernel-basecamp-2020, pull requests merged in 2020-02, with the labels that each got.

#3 A solution for hardware detector (hwdetect)
  README.md
  hwdetect/README.md
  hwdetect/hwdetect.sh
Labels: OK

#4 hwdetect
  README.md
  hwdetect/README.md
  hwdetect/hwdetect.sh
  hwdetect/log.txt
Labels: enhancement, ready for review, wontfix

#9 A solution for the second hw (device_tree)
  device_tree/Makefile
  device_tree/README.md
  device_tree/i2c_ol.c
  device_tree/world.dts
Labels: OK

#10 A solution for the third hw (timer)
  memory/README.md
  timer/Makefile
  timer/README.md
  timer/mytimer.c
  timer/userspace_time.c
Labels: ready for review

#23 Homework1 : hwdetect
  hwdetect/README.md
  hwdetect/hwdetect.sh
Labels: ready for review

#20 device tree
  device_tree/driver/Makefile
  device_tree/driver/mpu6050-regs.h
  device_tree/driver/mpu6050.c
  device_tree/dts_test.sh
  device_tree/log.txt
  device_tree/sun8i-h3-mpu6050.dts
  memory/README.md
  timer/README.md
Labels: ready for review

#17 A solution for device tree (dt)
  .editorconfig
  dt/armbianEnv.txt
  dt/sun8i-h3-bme280-overlay.dts
  dt/sun8i-h3-i2c0-overlay.dts
  dt/sun8i-h3-orangepi-one.dts
Labels: ready for review

#26 Homework4 : memory(userspace)
  memory/mem.c
Labels: OK

#19 A driver for tsl2580
  tsl2580/Makefile
  tsl2580/tsl2580.c
  tsl2580/tsl2580.dts
  tsl2580/tsl2580_regs.h
Labels: OK

#31 (1/2) A solution for time management (timer)
  .editorconfig
  memory/README.md
  timer/README.md
  timer/uspace/.clang-format
  timer/uspace/.gitignore
  timer/uspace/Makefile
  timer/uspace/src/main.c
Labels: OK
